export const chatNames = {
  "allchat": "General Chat",
  "gopchat": "General Operations Chat",
  "gschat": "General Security Chat",
  "cschat": "Customer Service Chat",
  "idchat": "Information Desk Chat",
  "lfchat": "Lost and Found Chat",
  "cichat": "Check-in Chat",
  "gachat": "Gate Chat",
  "aochat": "Airport Operations Chat",
  "fochat": "Flight Operations Chat",
  "ghchat": "Ground Handling Chat",
  "lochat": "Landside Operations Chat",
  "mtchat": "Maintenance Chat",
  "cbchat": "Custom and Border Control Chat",
  "bschat": "Baggage Security Chat",
  "carchat": "Cargo Chat",
  "logchat": "Logistics Chat",
  "cechat": "Civil Engineering Chat",
}
