export const roles = {
  "csm": "Customer Service Manager",
  "ids": "Information Desk Staff",
  "lfs": "Lost and Found Staff",
  "cis": "Check-in Staff",
  "ga": "Gate Agents",
  "aom": "Airport Operations Manager",
  "fom": "Flight Operations Manager",
  "ghm": "Ground Handling Manager",
  "ghs": "Ground Handling Staff",
  "lom": "Lanside Operations Manager",
  "mm": "Maintenance Manager",
  "ms": "Maintenance Staff",
  "cbco": "Customs and Border Control Officers",
  "bssu": "Baggage Security Supervisor",
  "bsst": "Baggage Security Staff",
  "cm": "Cargo Manager",
  "lm": "Logistic Manager",
  "fm": "Fuel Manager",
  "ch": "Cargo Handlers",
  "cem": "Civil Engineering Manager",
  "ceo": "Airport Director/CEO",
  "cfo": "Chief Financial Officer/CFO",
  "coo": "Chief Operations Officer/COO",
  "cso": "Chief Security Officer/CSO",
  "hrd": "Human Resource Director",
}
